CREATE DATABASE unow_challenge;
-- use unow_challenge;
--
-- CREATE TABLE vehicle(
--     id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     brand varchar(100),
--     model varchar(100),
--     licensePlate varchar(100),
--     color varchar(100),
--     year varchar(100)
-- );
-- INSERT INTO vehicle (brand, model, licensePlate, color, year)
-- VALUES("Tesla", "S", "RCB123", "green", "2022"), ("Tesla", "Y", "UJK123", "red", "2020"),
--       ("Tesla", "3", "QWE123", "green", "2022"), ("Toyota", "Yaris", "UGF123", "red", "2020"),
--       ("Toyota", "Supra", "GFT123", "green", "2022"), ("Toyota", "Corolla", "TYR123", "red", "2020");